source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!

target 'FacebookAdapter' do
   pod 'Google-Mobile-Ads-SDK', '~> 7.50.0'
   pod 'FBAudienceNetwork', '~> 5.6.0'
end

